name: Szymon Przedwojski
description: My thoughts on software development
meta_description: "Szymon Przedwojski, My thoughts on software development"

highlighter: rouge
logo: false
paginate: 15
domain_name: 'http://przedwojski.com'
google_analytics: 'UA-72598800-1'
gems: [jekyll-paginate]
permalink: pretty

# Details for the RSS feed generator
prod_url:       'http://przedwojski.com'
author:         'Szymon Przedwojski'

author_description: "I'm a software developer and a problem solver."

about_url: /about

github: 'sprzedwojski'
twitter: 'sprzedwojski'
linkedin: 'szymon-przedwojski-99534862'
